apiVersion: v1
kind: Secret
metadata:
  name: chat-service-secret
  namespace: blink-chat
  labels:
    app: chat-service
type: Opaque
data:
  JWT_SECRET: "MmU4MDRXQll3Nk************************"
  
  MONGODB_URI: "bW9uZ29kYjovL2FkbW****************************"

  REDIS_HOST: "cmVkaXMtMTA3OTAuY3JjZTI3Ni***************************"
  REDIS_PORT: "*****"
  REDIS_USERNAME: "*******"
  REDIS_PASSWORD: "*******************BWb1I2Q1g3aUl2WGI="

  SPRING_MAIL_USERNAME: "****************GdtYWlsLmNvbQ=="
  SPRING_MAIL_PASSWORD: "cmphbXFran**************************="

  TWILIO_ACCOUNT_SID: "U0szMzAxZjgwY******************************wZTc4ZA=="
  TWILIO_AUTH_TOKEN: "RVN3cF*****************************4SWc4ZkJPSjk="
  
  AI_API_KEY: "c2s************************************************************************ST2FIOHEzaWxpelJ5SUE="