apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: blink-chat

namespace: blink-chat

resources:
  - namespace.yaml
  - rbac.yaml
  - backend/configmap.yaml
  - backend/secret.yaml
  - backend/deployment.yaml
  - storage-class.yaml
  - backend/service.yaml
  - databases/mongodb.yaml
  - backend/hpa.yaml
  - ingress.yaml

images:
  - name: raajkr07/blink-chat-service
    newTag: main-1cf0001

labels:
  - pairs:
      app.kubernetes.io/name: blink-chat
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false