apiVersion: v1
kind: Service
metadata:
  name: frontend-v1
  namespace: blink-chat
  labels:
    app: frontend-v1
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend-v1